INSERT into CATEGORY (description) VALUES ('American');
INSERT into CATEGORY (description) VALUES ('Italian');
INSERT into CATEGORY (description) VALUES ('Mexican');
INSERT into CATEGORY (description) VALUES ('Fast food');
INSERT into CATEGORY (description) VALUES ('Indian');
INSERT into unit_of_measure (description) VALUES ('Teaspoon');
INSERT into unit_of_measure (description) VALUES ('Tablespoon');
INSERT into unit_of_measure (description) VALUES ('Ounce');
INSERT into unit_of_measure (description) VALUES ('Cup');
INSERT into unit_of_measure (description) VALUES ('Inch');
INSERT into unit_of_measure (description) VALUES ('slices');
